# Generated by Django 2.0.2 on 2018-04-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('homework', models.CharField(max_length=1000)),
                ('preview', models.CharField(max_length=1000)),
                ('topic', models.CharField(max_length=1000)),
                ('guide', models.CharField(max_length=1000)),
                ('target', models.CharField(max_length=1000)),
                ('opentopic', models.CharField(max_length=1000)),
            ],
        ),
    ]
